### ISSUE TITLE
package ‘stringdistr’ is not available (for R version 3.4.3)

### ISSUE THREAD

**Issue by tom-snir** [pogorely/ALICE#1]
Hello,

In the installation section of the read.me we are asked to install.packages("stringdistr"). However I am getting the error in the title. 

Any chance the package is supposed to be 'stringdist' and not 'stringdistr' ?ALICE.R mentions 'stringdist' only as well.

Thanks,

Tom Snir.

**Comment by pogorely** [comment]
Hi, Tom!

This is a typo, I fixed it. 
Thanks a lot for reporting!

Misha
