### ISSUE TITLE
Quick start example fails to run

### ISSUE THREAD

**Issue by Tsmith-87** [pogorely/ALICE#9]
Hi Mikhail,

Really great work and ALICE would be a great tool to apply to my data set. I'm having trouble with the quick start example though. When I run:

`S1_alice<-ALICE_pipeline(DTlist=S1,folder="S1_res",cores=1,iter=10,nrec=5e5)` 

I receive the error:

 `Error in D > 2 :` 
  `comparison (6) is possible only for atomic and list types` 

I get this error on 2 different machines so I don't think this is to do with my R session. I also receive the same error when applying the code to the example data used by wyattmcdonnell in the 'some bugs?' issue. 

Any advice on what could be causing this?

Thanks in advance,

Tasha

**Comment by pogorely** [comment]
Dear Tasha,

Thanks for the feedback!
Sorry for this. There was a bug indeed, this should be fixed now, please download the new version and try again. 

Misha

**Comment by Tsmith-87** [comment]
Hi Misha,

Thank you for such a quick response. I downloaded the new version and the example runs perfectly now. Thanks for your help, really appreciated!

Tasha

**Comment by pogorely** [comment]
you are welcome!
